# Generated by Django 4.2 on 2023-04-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('low_24h', models.FloatField()),
                ('high_24h', models.FloatField()),
                ('avg_24h', models.FloatField()),
                ('volume_24h', models.FloatField()),
                ('day', models.TextField()),
                ('week', models.TextField()),
                ('mount', models.TextField()),
            ],
        ),
    ]
